- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: what is your username?
    provate: no
  tasks:
  - name: print credentials
    ansible.builtin.debug:
      msg: "Hello, Username is: {{ usernam }}"